const fs = require('node:fs');
const { load } = require('./load-typescript.cjs');
const { lessons } = load('src/data.ts');
const words = [...lessons];
fs.writeFileSync(
  'assets/audio/words.json',
  JSON.stringify(
    Object.fromEntries(words.map((word) => [word.id, word.arabic])),
    null,
    2,
  ) + '\n',
);
const imports = words
  .map(
    (word) =>
      `  ${JSON.stringify(word.id)}: require('../assets/audio/${word.id}.wav'),`,
  )
  .join('\n');
fs.writeFileSync(
  'src/audio.ts',
  `// Generated by npm run audio:sync. Metro needs literal require paths.\nexport const audio: Record<string, number> = {\n${imports}\n};\n`,
);
console.log(
  `Synced ${words.length} audio entries from src/data.ts. WAV recordings are not changed.`,
);

const { arabicColors } = load('src/color-data.ts');
fs.mkdirSync('assets/audio/colors', { recursive: true });
fs.writeFileSync(
  'assets/audio/colors/words.json',
  JSON.stringify(
    Object.fromEntries(arabicColors.map((color) => [color.id, color.arabic])),
    null,
    2,
  ) + '\n',
);
const colorImports = arabicColors
  .map(
    (color) =>
      `  ${JSON.stringify(color.id)}: require('../assets/audio/colors/${color.id}.mp3'),`,
  )
  .join('\n');
fs.writeFileSync(
  'src/color-audio.ts',
  `// Generated by npm run audio:sync. Metro needs literal require paths.\nexport const colorAudio: Record<string, number> = {\n${colorImports}\n};\n`,
);
console.log(
  `Synced ${arabicColors.length} color audio entries. MP3 recordings are not changed.`,
);

const { arabicNumbers } = load('src/number-data.ts');
fs.mkdirSync('assets/audio/numbers', { recursive: true });
fs.writeFileSync(
  'assets/audio/numbers/words.json',
  JSON.stringify(
    Object.fromEntries(
      arabicNumbers.map((number) => [number.value, number.arabic]),
    ),
    null,
    2,
  ) + '\n',
);
const numberImports = arabicNumbers
  .map(
    (number) =>
      `  ${number.value}: require('../assets/audio/numbers/${number.value}.mp3'),`,
  )
  .join('\n');
fs.writeFileSync(
  'src/number-audio.ts',
  `// Generated by npm run audio:sync. Metro needs literal require paths.\nexport const numberAudio: Record<number, number> = {\n${numberImports}\n};\n`,
);
console.log(
  `Synced ${arabicNumbers.length} number audio entries. MP3 recordings are not changed.`,
);
