const fs = require('node:fs');
const { load } = require('./load-typescript.cjs');
const { lessons } = load('src/data.ts');
const words = [...lessons];
fs.writeFileSync(
  'assets/audio/words.json',
  JSON.stringify(
    Object.fromEntries(words.map((word) => [word.id, word.arabic])),
    null,
    2,
  ) + '\n',
);
const imports = words
  .map(
    (word) =>
      `  ${JSON.stringify(word.id)}: require('../assets/audio/${word.id}.wav'),`,
  )
  .join('\n');
fs.writeFileSync(
  'src/audio.ts',
  `// Generated by npm run audio:sync. Metro needs literal require paths.\nexport const audio: Record<string, number> = {\n${imports}\n};\n`,
);
console.log(
  `Synced ${words.length} audio entries from src/data.ts. WAV recordings are not changed.`,
);
