export type ArabicColor = {
  id: string;
  english: string;
  arabic: string;
  say: string;
  hex: string;
};

// Color adjectives are taught in their masculine singular dictionary form.
export const arabicColors: ArabicColor[] = [
  {
    id: 'red',
    english: 'Red',
    arabic: 'أَحْمَر',
    say: 'ahmar',
    hex: '#E53935',
  },
  {
    id: 'blue',
    english: 'Blue',
    arabic: 'أَزْرَق',
    say: 'azraq',
    hex: '#246BCE',
  },
  {
    id: 'yellow',
    english: 'Yellow',
    arabic: 'أَصْفَر',
    say: 'asfar',
    hex: '#FDD835',
  },
  {
    id: 'green',
    english: 'Green',
    arabic: 'أَخْضَر',
    say: 'akhdar',
    hex: '#309447',
  },
  {
    id: 'orange',
    english: 'Orange (color)',
    arabic: 'بُرْتُقَالِيّ',
    say: 'burtuqaaliyy',
    hex: '#FB8C00',
  },
  {
    id: 'purple',
    english: 'Purple',
    arabic: 'بَنَفْسَجِيّ',
    say: 'banafsajiyy',
    hex: '#8E44AD',
  },
  {
    id: 'pink',
    english: 'Pink',
    arabic: 'وَرْدِيّ',
    say: 'wardiyy',
    hex: '#F48FB1',
  },
  {
    id: 'brown',
    english: 'Brown',
    arabic: 'بُنِّيّ',
    say: 'bunniyy',
    hex: '#795548',
  },
  {
    id: 'black',
    english: 'Black',
    arabic: 'أَسْوَد',
    say: 'aswad',
    hex: '#202124',
  },
  {
    id: 'white',
    english: 'White',
    arabic: 'أَبْيَض',
    say: 'abyad',
    hex: '#FFFFFF',
  },
  {
    id: 'gray',
    english: 'Gray',
    arabic: 'رَمَادِيّ',
    say: 'ramaadiyy',
    hex: '#90949C',
  },
  {
    id: 'gold',
    english: 'Gold',
    arabic: 'ذَهَبِيّ',
    say: 'dhahabiyy',
    hex: '#D4AF37',
  },
  {
    id: 'silver',
    english: 'Silver',
    arabic: 'فِضِّيّ',
    say: 'fiddiyy',
    hex: '#C0C0C0',
  },
  {
    id: 'turquoise',
    english: 'Turquoise',
    arabic: 'فَيْرُوزِيّ',
    say: 'fayrooziyy',
    hex: '#40CFC4',
  },
  {
    id: 'navy',
    english: 'Navy blue',
    arabic: 'كُحْلِيّ',
    say: 'kuhliyy',
    hex: '#182B58',
  },
  {
    id: 'sky',
    english: 'Sky blue',
    arabic: 'سَمَاوِيّ',
    say: 'samaawiyy',
    hex: '#80CEF1',
  },
  {
    id: 'olive',
    english: 'Olive green',
    arabic: 'زَيْتُونِيّ',
    say: 'zaytooniyy',
    hex: '#808032',
  },
  {
    id: 'beige',
    english: 'Beige',
    arabic: 'بَيْج',
    say: 'bayj',
    hex: '#E5D3B3',
  },
  {
    id: 'ivory',
    english: 'Ivory',
    arabic: 'عَاجِيّ',
    say: '‘aajiyy',
    hex: '#FFFFE5',
  },
  {
    id: 'copper',
    english: 'Copper',
    arabic: 'نُحَاسِيّ',
    say: 'nuhaasiyy',
    hex: '#B87333',
  },
  {
    id: 'maroon',
    english: 'Maroon',
    arabic: 'عُنَّابِيّ',
    say: '‘unnaabiyy',
    hex: '#800030',
  },
  {
    id: 'coral',
    english: 'Coral',
    arabic: 'مَرْجَانِيّ',
    say: 'marjaaniyy',
    hex: '#FF7F66',
  },
  {
    id: 'peach',
    english: 'Peach',
    arabic: 'خَوْخِيّ',
    say: 'khawkhiyy',
    hex: '#FFCBA4',
  },
  {
    id: 'light-blue',
    english: 'Light blue',
    arabic: 'أَزْرَق فَاتِح',
    say: 'azraq faatih',
    hex: '#ADD8E6',
  },
  {
    id: 'light-green',
    english: 'Light green',
    arabic: 'أَخْضَر فَاتِح',
    say: 'akhdar faatih',
    hex: '#A5D98A',
  },
  {
    id: 'dark-green',
    english: 'Dark green',
    arabic: 'أَخْضَر دَاكِن',
    say: 'akhdar daakin',
    hex: '#18552C',
  },
  {
    id: 'light-pink',
    english: 'Light pink',
    arabic: 'وَرْدِيّ فَاتِح',
    say: 'wardiyy faatih',
    hex: '#FFD6E5',
  },
  {
    id: 'dark-purple',
    english: 'Dark purple',
    arabic: 'بَنَفْسَجِيّ دَاكِن',
    say: 'banafsajiyy daakin',
    hex: '#4B206A',
  },
  {
    id: 'light-brown',
    english: 'Light brown',
    arabic: 'بُنِّيّ فَاتِح',
    say: 'bunniyy faatih',
    hex: '#C49A72',
  },
  {
    id: 'dark-gray',
    english: 'Dark gray',
    arabic: 'رَمَادِيّ دَاكِن',
    say: 'ramaadiyy daakin',
    hex: '#4D5159',
  },
];
